### ISSUE TITLE
"Bad CPU type in executable" when running example

### ISSUE THREAD

**Issue by tylers-username** [wobsoriano/deno-systray#1]
When I attempt to copy and past the readme.md example or run `deno run -A https://deno.land/x/systray/example/index.ts` I get the following error on MacOS.
<img width="274" alt="image" src="https://user-images.githubusercontent.com/4887071/207078372-d9976058-0027-4436-8007-77f7431099b9.png">

```zsh
➜  urler deno run -A https://deno.land/x/systray/example/index.ts
Download ⠼ https://deno.land/x/systray/example/index.ts                                                                                                                                                                 Warning Implicitly using latest version (v0.2.2) for https://deno.land/x/systray/example/index.ts
error: Uncaught (in promise) Error: Bad CPU type in executable (os error 86)
    this._process = Deno.run({
                         ^
    at opRun (deno:runtime/js/40_process.js:33:16)
    at Object.run (deno:runtime/js/40_process.js:116:17)
    at SysTray.run (https://deno.land/x/systray@v0.2.2/mod.ts:241:26)
    at SysTray.init (https://deno.land/x/systray@v0.2.2/mod.ts:273:12)

```

**Comment by felipetesc** [comment]
I've ran into the same issue. The only culprit I found is related to Deno.run being depracated:
`Deno.run` is deprecated and scheduled for removal in Deno 2.0
Use `Deno.Command` from https://deno.land/api insteaddeno-lint(no-deprecated-deno-api)

**Comment by felipetesc** [comment]
> When I attempt to copy and past the readme.md example or run `deno run -A https://deno.land/x/systray/example/index.ts` I get the following error on MacOS. <img alt="image" width="274" src="https://user-images.githubusercontent.com/4887071/207078372-d9976058-0027-4436-8007-77f7431099b9.png">
> 
> ```shell
> ➜  urler deno run -A https://deno.land/x/systray/example/index.ts
> Download ⠼ https://deno.land/x/systray/example/index.ts                                                                                                                                                                 Warning Implicitly using latest version (v0.2.2) for https://deno.land/x/systray/example/index.ts
> error: Uncaught (in promise) Error: Bad CPU type in executable (os error 86)
>     this._process = Deno.run({
>                          ^
>     at opRun (deno:runtime/js/40_process.js:33:16)
>     at Object.run (deno:runtime/js/40_process.js:116:17)
>     at SysTray.run (https://deno.land/x/systray@v0.2.2/mod.ts:241:26)
>     at SysTray.init (https://deno.land/x/systray@v0.2.2/mod.ts:273:12)
> ```

What Deno version your are using ?

**Comment by rummik** [comment]
It looks like [systray-portable's build.sh](https://github.com/wobsoriano/systray-portable/blob/v0.1.2/build.sh) might not be building for platforms other than the build host
